# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import os
import pathlib
import typing
from . import single_judge

class Builder:
    def new(self) -> Builder:
        ...

    def add_static_text(self, name:builtins.str, content:builtins.str) -> Outcome:
        ...

    def add_runtime_text(self, name:builtins.str, label:builtins.str) -> Outcome:
        ...

    def add_empty_directory(self, name:builtins.str) -> Outcome:
        ...

    def add_script(self, name:builtins.str, content:builtins.str) -> Outcome:
        ...

    def add_execution(self, name:builtins.str, script:Outcome, dependencies:typing.Sequence[Dependency], time_reserved_ms:builtins.int) -> Outcome:
        ...

    def jsonify(self) -> builtins.str:
        ...

    def run(self, label_to_content:typing.Mapping[builtins.str, builtins.str], host_temp_dir:builtins.str | os.PathLike | pathlib.Path, container_temp_dir:builtins.str | os.PathLike | pathlib.Path, container_image_name:builtins.str) -> builtins.str:
        ...


class Dependency:
    def new(self, outcome:Outcome, envvar_name:builtins.str) -> Dependency:
        ...


class Outcome:
    ...

