# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum, auto

class ExecutionMetadata:
    r"""
    Judge input.
    """
    def new(self) -> ExecutionMetadata:
        r"""
        Read the input from environment variables.
        """
        ...


class JudgeStatus(Enum):
    r"""
    Judge status enum.
    """
    AC = auto()
    WA = auto()
    TLE = auto()
    MLE = auto()
    OLE = auto()
    RE = auto()
    CE = auto()

def displayable_result(status:JudgeStatus, time:builtins.float, memory:builtins.float, score:builtins.int, continue_next:builtins.bool, message:typing.Optional[builtins.str]) -> builtins.str:
    r"""
    Create a displayable result.
    """
    ...

def hidden_result(continue_next:builtins.bool) -> builtins.str:
    r"""
    Create a hidden result.
    """
    ...

