openapi: '3.0.3'
info:
  title: Judge to Backend API
  version: '0.1'
  license:
    name: MIT
    url: 'https://github.com/traP-jp/traO-Judge-docs/blob/main/LICENSE'
servers:
  - url: https://api.server.test/v1
paths:
  '/judge':
    post:
      operationId: judge
      description: 全てのジャッジ
      tags:
        - judge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Judge'
        required: true
      summary: 全てのジャッジ
      responses:
        '200':
          description: OK
components:
  schemas:
    Execution:
      title: Execution
      type: object
      description: テストケース実行時の実行時間など
      properties:
        optionalInfo:
          title: optionalInfo
          type: object
          description: 任意の情報
          properties:
            execTime:
              title: execTime
              type: number
              description: 実行時間
              example: 1.23
            memorySize:
              title: memorySize
              type: number
              description: メモリ使用量(byte)
              example: 123456789
            language:
              title: language
              type: string
              description: 使用言語
              example: python
        shellScriptId:
          title: shellScriptId
          type: string
          format: uuid
          description: シェルスクリプトのID
          example: 68ffddc4-adc6-4f93-9ff2-d862ee6cce7a
        directoryCount:
          title: directoryCount
          type: number
          description: ディレクトリの数
          example: 3
        textResourceCount:
          title: textResourceCount
          type: number
          description: テキストリソースの数
          example: 3
        oneTimeTextCount:
          title: oneTimeTextCount
          type: number
          description: テキストの数
          example: 3
      required:
        - shellScriptId
        - directoryCount
        - textResourceCount
        - oneTimeTextCount
    ExecutionConfigMap:
      title: ExecutionConfigMap
      type: object
      description: ジャッジの設定
      properties:
        textResourceIds:
          title: textResourceIds
          type: array
          description: 静的なテキストリソースのID
          items:
            type: string
            format: uuid
            example: 68ffddc4-adc6-4f93-9ff2-d862ee6cce7a
        oneTimeTextContents:
          title: oneTimeTextContents
          type: array
          description: 動的に変化するテキストデータ
          items:
            type: string
            example: |
              user-1: 100
              user-2: 200
    Judge:
      title: JudgeConfig
      type: object
      description: ジャッジの設定
      properties:
        judgeId:
          title: JudgeId
          type: string
          format: uuid
          description: ジャッジのID
          example: 68ffddc4-adc6-4f93-9ff2-d862ee6cce7a
        testCount:
          title: testCount
          type: number
          description: テストケースの数
          example: 3
        beforeTestExecs:
          $ref: '#/components/schemas/Execution'
        onTestExecs:
          $ref: '#/components/schemas/Execution'
        afterTestExecs:
          $ref: '#/components/schemas/Execution'
        beforeTestConfigMap:
          $ref: '#/components/schemas/ExecutionConfigMap'
        onTestConfigMaps:
          title: onTestConfigMaps
          type: array
          description: テストケース実行時に実行されるコマンドの設定
          items:
            $ref: '#/components/schemas/ExecutionConfigMap'
        afterTestConfigMap:
          $ref: '#/components/schemas/ExecutionConfigMap'
      required:
        - judgeId
        - testCount
        - beforeTestExecs
        - onTestExecs
        - afterTestExecs
        - beforeTestConfigMap
        - onTestConfigMaps
        - afterTestConfigMap