-- created_at を NOT NULL に変更
ALTER TABLE `editorials` 
MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- updated_at を NOT NULL に変更
ALTER TABLE `editorials` 
MODIFY COLUMN `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;