pub const SCRIPT_PATH: &str = "TRAOJUDGE_EXEC_SCRIPT";
pub const OUTPUT_PATH: &str = "TRAOJUDGE_EXEC_OUTPUT";
pub const LANGUAGES_JSON: &str = "TRAOJUDGE_LANGUAGES_JSON";
pub const BUILD_SOURCE: &str = "TRAOJUDGE_BUILD_SOURCE";
pub const BUILD_OUTPUT: &str = "TRAOJUDGE_BUILD_OUTPUT";
pub const BUILD_TEMPDIR: &str = "TRAOJUDGE_BUILD_TEMPDIR";
