/*
 * Judge to Backend API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileAccessibility : ファイルのアクセス権限
/// ファイルのアクセス権限
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileAccessibility {
    #[serde(rename = "invisible")]
    Invisible,
    #[serde(rename = "readonly")]
    Readonly,
    #[serde(rename = "readwrite")]
    Readwrite,

}

impl std::fmt::Display for FileAccessibility {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Invisible => write!(f, "invisible"),
            Self::Readonly => write!(f, "readonly"),
            Self::Readwrite => write!(f, "readwrite"),
        }
    }
}

impl Default for FileAccessibility {
    fn default() -> FileAccessibility {
        Self::Invisible
    }
}

