# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

from . import common
from . import v0

def _marker_fn() -> None:
    r"""
    Marker to ensure pyo3_stub_gen imports nested submodules
    """
    ...

