# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

def normal_judge_checker(expected:builtins.str, actual:builtins.str) -> builtins.bool:
    ...

def parse_whitespace_and_newline(s:builtins.str) -> builtins.str:
    ...

def read_file_with_envvar(envvar:builtins.str) -> builtins.str:
    ...

