# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing
from enum import Enum, auto

class ExecStats:
    time_ms: builtins.int
    memory_kib: builtins.int

class Language:
    ...

class Library:
    ...

class ExecResult(Enum):
    Success = auto()
    Timeout = auto()

class JudgeStatus(Enum):
    AC = auto()
    WA = auto()
    TLE = auto()
    MLE = auto()
    OLE = auto()
    RE = auto()
    CE = auto()

def exec_with_stats(cmd:builtins.str, envs:typing.Mapping[builtins.str, builtins.str], time_limit_ms:builtins.int) -> ExecResult:
    r"""
    Execute a command with environment variables and a time limit
    """
    ...

def get_language_info(language_tag:builtins.str) -> Language:
    ...

def jsonify_displayable_output(status:JudgeStatus, time_ms:builtins.float, memory_kib:builtins.float, score:builtins.int, continue_next:builtins.bool, message:typing.Optional[builtins.str]) -> builtins.str:
    ...

def jsonify_hidden_output(continue_next:builtins.bool) -> builtins.str:
    ...

