# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

def compile_phase() -> builtins.str:
    ...

def summary_phase() -> builtins.str:
    ...

def test_phase(core_name:builtins.str) -> builtins.str:
    ...

