# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

def language_tag() -> builtins.str:
    ...

def memory_limit_kib() -> builtins.str:
    ...

def submission_source() -> builtins.str:
    ...

def time_limit_ms() -> builtins.str:
    ...

