// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Unit {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Uuid {
    #[prost(uint64, tag = "1")]
    pub high: u64,
    #[prost(uint64, tag = "2")]
    pub low: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OptionalInfo {
    #[prost(float, optional, tag = "1")]
    pub time_limit: ::core::option::Option<f32>,
    #[prost(float, optional, tag = "2")]
    pub memory_limit: ::core::option::Option<f32>,
    #[prost(string, optional, tag = "3")]
    pub language: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Execution {
    #[prost(message, optional, tag = "1")]
    pub optional_info: ::core::option::Option<OptionalInfo>,
    #[prost(message, optional, tag = "2")]
    pub script_id: ::core::option::Option<Uuid>,
    #[prost(int64, tag = "3")]
    pub directory_count: i64,
    #[prost(int64, tag = "4")]
    pub text_resource_count: i64,
    #[prost(int64, tag = "5")]
    pub onetime_text_count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionInstance {
    #[prost(message, repeated, tag = "1")]
    pub text_resource_ids: ::prost::alloc::vec::Vec<Uuid>,
    #[prost(string, repeated, tag = "2")]
    pub onetime_texts: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JudgeRequest {
    #[prost(message, optional, tag = "1")]
    pub judge_id: ::core::option::Option<Uuid>,
    #[prost(int64, tag = "2")]
    pub test_count: i64,
    #[prost(message, optional, tag = "3")]
    pub before_test_execution: ::core::option::Option<Execution>,
    #[prost(message, optional, tag = "4")]
    pub on_test_execution: ::core::option::Option<Execution>,
    #[prost(message, optional, tag = "5")]
    pub after_test_execution: ::core::option::Option<Execution>,
    #[prost(message, optional, tag = "6")]
    pub before_test_execution_instance: ::core::option::Option<ExecutionInstance>,
    #[prost(message, repeated, tag = "7")]
    pub on_test_execution_instances: ::prost::alloc::vec::Vec<ExecutionInstance>,
    #[prost(message, optional, tag = "8")]
    pub after_test_execution_instance: ::core::option::Option<ExecutionInstance>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecutionResult {
    #[prost(enumeration = "JudgeStatus", tag = "1")]
    pub status: i32,
    #[prost(string, optional, tag = "2")]
    pub message: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(float, tag = "3")]
    pub score: f32,
    #[prost(float, tag = "4")]
    pub execution_time: f32,
    #[prost(float, tag = "5")]
    pub used_memory: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminatedInBeforeTestPhase {
    #[prost(message, optional, tag = "1")]
    pub before_test_execution_result: ::core::option::Option<ExecutionResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TerminatedInOnTestPhase {
    #[prost(message, optional, tag = "1")]
    pub before_test_execution_result: ::core::option::Option<ExecutionResult>,
    #[prost(message, repeated, tag = "2")]
    pub on_test_execution_results: ::prost::alloc::vec::Vec<ExecutionResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Completed {
    #[prost(message, optional, tag = "1")]
    pub before_test_execution_result: ::core::option::Option<ExecutionResult>,
    #[prost(message, repeated, tag = "2")]
    pub on_test_execution_results: ::prost::alloc::vec::Vec<ExecutionResult>,
    #[prost(message, optional, tag = "3")]
    pub after_test_execution_result: ::core::option::Option<ExecutionResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JudgeSucceed {
    #[prost(oneof = "judge_succeed::Result", tags = "1, 2, 4")]
    pub result: ::core::option::Option<judge_succeed::Result>,
}
/// Nested message and enum types in `JudgeSucceed`.
pub mod judge_succeed {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        TerminatedInBeforeTestPhase(super::TerminatedInBeforeTestPhase),
        #[prost(message, tag = "2")]
        TerminatedInOnTestPhase(super::TerminatedInOnTestPhase),
        #[prost(message, tag = "4")]
        Completed(super::Completed),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FailedInBeforeTestPhase {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FailedInOnTestPhase {
    #[prost(message, optional, tag = "1")]
    pub before_test_execution_result: ::core::option::Option<ExecutionResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FailedInAfterTestPhase {
    #[prost(message, optional, tag = "1")]
    pub before_test_execution_result: ::core::option::Option<ExecutionResult>,
    #[prost(message, repeated, tag = "2")]
    pub on_test_execution_results: ::prost::alloc::vec::Vec<ExecutionResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JudgeFailed {
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
    #[prost(oneof = "judge_failed::Result", tags = "1, 2, 3")]
    pub result: ::core::option::Option<judge_failed::Result>,
}
/// Nested message and enum types in `JudgeFailed`.
pub mod judge_failed {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        FailedInBeforeTestPhase(super::FailedInBeforeTestPhase),
        #[prost(message, tag = "2")]
        FailedInOnTestPhase(super::FailedInOnTestPhase),
        #[prost(message, tag = "3")]
        FailedInAfterTestPhase(super::FailedInAfterTestPhase),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JudgeResult {
    #[prost(message, optional, tag = "1")]
    pub judge_id: ::core::option::Option<Uuid>,
    #[prost(oneof = "judge_result::Result", tags = "2, 3")]
    pub result: ::core::option::Option<judge_result::Result>,
}
/// Nested message and enum types in `JudgeResult`.
pub mod judge_result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "2")]
        JudgeSucceed(super::JudgeSucceed),
        #[prost(message, tag = "3")]
        JudgeFailed(super::JudgeFailed),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum JudgeStatus {
    Ac = 0,
    Wa = 1,
    Tle = 2,
    Mle = 3,
    Ole = 4,
    Re = 5,
    Ce = 6,
}
impl JudgeStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ac => "AC",
            Self::Wa => "WA",
            Self::Tle => "TLE",
            Self::Mle => "MLE",
            Self::Ole => "OLE",
            Self::Re => "RE",
            Self::Ce => "CE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AC" => Some(Self::Ac),
            "WA" => Some(Self::Wa),
            "TLE" => Some(Self::Tle),
            "MLE" => Some(Self::Mle),
            "OLE" => Some(Self::Ole),
            "RE" => Some(Self::Re),
            "CE" => Some(Self::Ce),
            _ => None,
        }
    }
}
/// Generated server implementations.
pub mod judge_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with JudgeServiceServer.
    #[async_trait]
    pub trait JudgeService: std::marker::Send + std::marker::Sync + 'static {
        async fn judge(
            &self,
            request: tonic::Request<super::JudgeRequest>,
        ) -> std::result::Result<tonic::Response<super::JudgeResult>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct JudgeServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> JudgeServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for JudgeServiceServer<T>
    where
        T: JudgeService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/JudgeService/Judge" => {
                    #[allow(non_camel_case_types)]
                    struct JudgeSvc<T: JudgeService>(pub Arc<T>);
                    impl<
                        T: JudgeService,
                    > tonic::server::UnaryService<super::JudgeRequest> for JudgeSvc<T> {
                        type Response = super::JudgeResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::JudgeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JudgeService>::judge(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = JudgeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for JudgeServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "JudgeService";
    impl<T> tonic::server::NamedService for JudgeServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
