# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import os
import pathlib
import typing
from enum import Enum, auto

class Dependency:
    r"""
    Dependency object to refer to previous output.
    
    Path to the output will be provided as an environment variable named `envvar_name`.
    """
    def __new__(cls,ref_to:Output, envvar_name:builtins.str): ...
    ...

class EmptyDirectory:
    r"""
    Empty directory object to be placed in the execution environment.
    """
    def __new__(cls,name:builtins.str): ...
    ...

class Execution:
    r"""
    Execution object to be executed
    
    Script will be run with paths as environment variables specified in `depends_on`.
    """
    def __new__(cls,name:builtins.str, script:ScriptOutput, depends_on:typing.Sequence[Dependency]): ...
    ...

class LocalJudge:
    r"""
    LocalJudge object to run provided procedures in your local environment.
    """
    def __new__(cls,temp_dir:builtins.str | os.PathLike | pathlib.Path): ...
    def run(self, builder:ProcedureBuilder, runtime_text_contents:typing.Mapping[builtins.str, builtins.str]) -> builtins.str:
        r"""
        Run the provided procedure in your local environment.
        """
        ...


class Output:
    r"""
    Output object of each job.
    
    Executions can depend on Output by passing Output object to `depends_on` field of Execution.
    """
    ...

class ProcedureBuilder:
    r"""
    ProcedureBuilder object to build a procedure.
    """
    def __new__(cls,): ...
    def add_resource(self, resource:ResourceKind) -> Output:
        r"""
        Add a resource to the procedure.
        """
        ...

    def add_script(self, script:Text) -> ScriptOutput:
        r"""
        Add a script to the procedure.
        """
        ...

    def add_execution(self, execution:Execution) -> Output:
        r"""
        Add an execution to the procedure.
        """
        ...

    def write_to(self, path:builtins.str | os.PathLike | pathlib.Path) -> None:
        r"""
        Export the procedure to a json file.
        """
        ...


class RuntimeText:
    r"""
    RuntimeText object to be placed in the execution environment.
    
    `label`s have corresponding types of resources determined in judge-run time.
    | label | description |
    | --- | --- |
    | `source` | Submission source code |
    | `time_limit` | Time limit(optional) |
    | `memory_limit` | Memory limit(optional) |
    | `language` | Language of the submission(optional) |
    """
    def __new__(cls,name:builtins.str, label:builtins.str): ...
    ...

class ScriptOutput:
    ...

class Text:
    r"""
    Text object to be placed in the execution environment.
    
    Contents of Text must be static.
    """
    def __new__(cls,name:builtins.str, path:builtins.str | os.PathLike | pathlib.Path): ...
    ...

class ResourceKind(Enum):
    r"""
    Resource object to be placed in the execution environment.
    
    EmptyDirectory is an directory and TextFile and RuntimeTextFile are files.
    """
    EmptyDirectory = auto()
    RuntimeTextFile = auto()
    TextFile = auto()

