name: Integration test(backend)

on:
  workflow_call:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
 test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: world
          TZ: Asia/Tokyo
        ports:
          - 3306:3306
        options: --health-cmd="mariadb-admin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}_Integration_test(backend)
        
    - name: run minio
      run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=access_key" \
                     -e "MINIO_SECRET_KEY=secret_key" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data

    - name: Run migrate
      working-directory: lib/backend_infra
      env:
        DATABASE_URL: mysql://root:password@localhost:3306/world
      run: cargo install sqlx-cli && cargo sqlx migrate run

    - name: Run backend test
      env:
        CODEGEN_SKIP: true
      run: source app/backend_app/.env.dev && cargo test -- --ignored backend
