name: _test-queue-app

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"


jobs:
 test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./queue-app
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    
    - name: Build test
      run: cargo build
    - name: Run test
      run: cargo test
    - name: Lint with clippy
      run: cargo clippy --all-targets --all-features -- -A dead_code
    - name: Check formatting
      run: cargo fmt --all --check